export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const CLEAR_ERRORS = "CLEAR_ERRORS";

export const REGISTER_USER_FAIL = "LOGIN_REQUEST";
export const REGISTER_USER_REQUEST = "LOGIN_SUCCESS";
export const REGISTER_USER_SUCCESS = "LOGIN_FAIL";

// export const PRODUCT_DETAILS_REQUEST = "PRODUCT_DETAILS_REQUEST";
// export const PRODUCT_DETAILS_SUCCESS = "PRODUCT_DETAILS_SUCCESS";
// export const PRODUCT_DETAILS_FAIL = "PRODUCT_DETAILS_FAIL";